### ISSUE TITLE
Selecting from pop-up box causes cursor to skip one or more lines

### ISSUE THREAD

**Issue by mjshowalter** [adapt-it/adapt-it-mobile#299] opened 2018-03-20 03:28 UTC
Adapt It Mobile Version:  Don't know, downloaded 3/17/2018

Operating System: Android

OS Version: Android 7.0

Samsung Galaxy J7 Perx

Severity: 3

Description: When I selected a word in the source text that had multiple translations in the target text, then selected a word from the pop-up box, the highlight went to the next row, skipping a row of text.  Sometimes it skipped multiple rows.  I was expecting it to stay on the same word, or move to the next word on the same line.

Steps to Reproduce:

1. Select a word that has multiple translations
2. Select a word in the pop-up box in the target language
3. In the source text, observe that the highlight is now on the next line, or a lower line, depending on how many lines were in the pop-up box.  One or more rows of text were skipped.

Madeleine Showalter

**Comment by eb1** [comment] 2018-03-23 01:43
Initial comments on this issue:

I'm unable to reproduce this issue on iOS or Android under simulation. My _suspicion_ is that this might be due to older Android browser implementations of popover text rendering (see issues #149 and #237), causing the "click" to be registered on the layer underneath the menu. I'll need to investigate further to verify.

**Comment by mjshowalter** [comment] 2018-03-23 03:17
Using Android 7.0

**Comment by eb1** [comment] 2018-04-09 19:42
Marking this as closed (unfortunately, there's no "pending" state for GitHub). Please retest this issue with the latest version on the PhoneGap build site (https://build.phonegap.com/apps/713362/share), and reopen if necessary. 

While I've not been able to reproduce this issue on this side, I *have* made several changes to the dropdown menu stylings that have increased the size of the clickable area. I'm wondering if this issue has been resolved with the changes, or if there is still some other problem that needs to be addressed. Thanks so much!

**Closed** 2018-04-09 19:42 UTC
