### ISSUE TITLE
"Reset Adapt It Mobile" - Dangerous

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#125] opened 2015-11-06 23:14 UTC
Adapt It Mobile Version: 0.4.5
Operating System: Android
OS Version: Android 4.4.2
Severity: 2
Description: After doing some adapting in my 3 John 1 document, I clicked on < in the title bar and went back to the project page (that lists the Project Settings and other buttons). I happened to then click on the title bar (on the "Nyindrou to Tok Pisin Adaptations" text), and up popped this message:
[Title] Reset Adapt It Mobile
WARNING: This will clear all documents and projects, as well as the Knowledge Base. Are you sure you want to reset Adapt It Mobile? [OK] [Cancel]"
I was surprised to see this pop up in response to a tap on the title bar at the main project page. I was looking for a < icon at the upper left of the main project page in order to go back to try and create a second project on AIM. There is no way to get back to the Get Started page once one project has been created, so I assume having more than one project is not yet implemented in this alpha version. I did not see a < icon on the title bar, but when I tapped around on the title bar I got the above rather dangerous message, which I think should not appear as the result of a tap on the title bar in one's current project. Since I had not created a lot of adaptation work in the current project I decided to see if the warning was accurate. Yes indeed! Clicking OK at that warning does indeed result in a wipe out of all project data - followed by the "Welcome to Adapt It Mobile" greeting, and [Continue] to the initial "Get Started" page. Even in AID we don't provide a way to directly remove or wipe out an entire project and all its data, kb, etc. (though a user could do so by starting a file manager, navigating to AID's Adapt It Unicode Work folder and deleting either that folder or a project folder within AID's Adapt It Unicode Work folder).

**Comment by eb1** [comment] 2015-11-06 23:45
Closing this as wontfix / as designed.

To even get this dialog to appear, you have to tap the title bar FIVE TIMES. Once it appears, you have to click the OK button to a pretty explicit warning. AI desktop has the same functionality, available by holding the shift key (a single keystroke) while launching.

**Comment by pngbill** [comment] 2015-11-07 01:39
Of course, holding the shift key in AID will reset the configuration files to a default state. I don't know of any key combination anywhere in AID that will destroy all data, kbs, documents, etc - the equivalent of deleting the whole work folder. I still think it is too dangerous. Is it something that is controlled by the Android system, or something which you provided in AIM?

**Comment by adaptitbruce** [comment] 2015-11-07 04:23
No, it's not really the same functionality in AID. Holding the SHIFT key down when launching only bypasses the utilization of one or both configuration files - you get a default configuration, but no projects are altered, no data lost or moved, no documents affected etc.

--Bruce
  ----- Original Message -----

**Comment by adaptitbruce** [comment] 2015-11-07 04:29
----- Original Message -----

**Comment by eb1** [comment] 2015-11-08 23:01
Reopening issue: it looks like I'm outvoted. :-) 

I'll add a password to the feature, so that this cannot be activated by accidental clicks. Hopefully this satisfies the "escalating options" requirement -- in order to reset AIM, the user will have to:

1. Click 5 times on the title bar of the main screen without clicking off to another screen.
2. Know and type in the appropriate password.
3. Click Yes on the explicit warning that tells them the ramifications of resetting AIM.

**Closed** 2015-11-08 23:02 UTC
Labels: wontfix

**Comment by adaptitbruce** [comment] 2015-11-09 00:26
On 9/11/2015 10:01 AM, Erik Brommers wrote:
>
> Reopening issue: it looks like I'm outvoted. :-)
>
> I'll add a password to the feature, so that this cannot be activated
> by accidental clicks. Hopefully this satisfies the "escalating
> options" requirement -- in order to reset AIM, the user will have to:
>
>  1. Click 5 times on the title bar of the main screen without clicking
>     off to another screen.
>  2. Know and type in the appropriate password.
>  3. Click Yes on the explicit warning that tells them the
>     ramifications of resetting AIM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adapt-it/adapt-it-mobile/issues/125#issuecomment-154884319>.
>
Sounds right. Thanks Erik --Bruce
