### ISSUE TITLE
AIM not offering choice of translation equivalents

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#122] opened 2015-11-06 00:17 UTC
Adapt It Mobile Version: 0.4.5
Operating System: Android
OS Version: [e.g., Android 4.4.2] 
Severity: [2 - missing basic functionality of adaptation work]
Description:
After translating a given source word or phrase more than one way, AIM should provide a list of those translation equivalents the next time the word or phrase is encountered in the adaptation process. However, AIM automatically enters only one of the translation equivalents (the first one used it seems) and advances, rather than pausing and presenting the user with a list of previously used translation equivalents to choose from. Providing a choice of translation equivalents is one of the basic features that makes AI useful as a translation tool - giving the user the opportunity to easily choose between possible translations without having to type out an equivalent that better fits the current context, or (as currently necessary) always going back to manually change an automatically entered wrong equivalent for the correct one.
Suggestion:
On my Android devices, there is an area directly above the keyboard that makes suggestions as you type - displaying possible words that might be intended and that can be substituted with a single tap. This mechanism is currently based on English word completion, and as such is useless for AIM, and currently just wastes one or two lines of precious screen real estate. But if this word/phrase completion could be harnessed under AIM as the equivalent of AID's "Choose Translation" dialog - displaying all known translation equivalents, it could be the area of the screen where such target text translation equivalents could be displayed rather than presenting a popup choice dialog as AID does.

**Comment by eb1** [comment] 2015-11-06 20:14
This is a duplicate of issue #85.

**Closed by eb1** 2015-11-06 20:14 UTC
Labels: duplicate
