### ISSUE TITLE
Merge a Phrase failures

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#103] opened 2015-09-02 18:10 UTC
I've found that the Merge a Phrase feature is inconsistent. I've been able to select and merge two source words into a phrase, but it seems to fail on attempts to merge 3 or more words. After such a failure, it won't merge even two words any more - until I shut down the app and restart.

**Comment by eb1** [comment] 2015-09-03 14:43
Hi Bill,

I've been able to merge > 3 words on iOS, Android and in the browser (screen shots for ios and browser below for reference). Can you provide a reproduction scenario here? Thanks!

![image](https://cloud.githubusercontent.com/assets/1458944/9661210/4f1ea6de-521f-11e5-8f60-c0963b9fe409.png)
 ![image](https://cloud.githubusercontent.com/assets/1458944/9661100/c71f0e40-521e-11e5-9bcc-27846d7865a9.png)

**Comment by pngbill** [comment] 2015-09-03 15:10
Hi Erik,

On my Moto G phone and also on my Samsung Galaxy Tab 3 (7"), I could 
also merge two or more words on the first attempt during a given 
session, but invariably successive attempts to merge words would fail. I 
could select words for a successive merger and click on the merge icon, 
but nothing would happen.

Today I'm having trouble selecting more than one source word on the 
tablet's touch screen within AIM (using a source text file that contains 
Matthew chapter 9, so I can't seem to get a situation where I can even 
try out the merging process.

I think it would be good to sit down in person with my devices at some 
point at we can more easily see how the process goes on my devices. 
Today is my birthday, and we are planning some family things this 
weekend. I'll try to work out something with you early next week.

Thanks,

Bill

**Comment by eb1** [comment] 2015-10-05 22:48
Selection cleanup looks like it's addressed this issue as well -- closing.

**Closed by eb1** 2015-10-05 22:48 UTC
