### ISSUE TITLE
Unable to import Tok Pisin fragment of 1 John

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#131] opened 2015-12-15 23:37 UTC
Adapt It Mobile Version: 0.5.0
Operating System: Android
OS Version: Android 4.4.2
Severity: 3
Description: After opening a new chapter document, I expect that the initial document listed on the project page would be the actual document containing the chapter and verse content. Instead the initial document listed is a truncated document that when opened only has the \id line available for adaptation. In order to get the actual document I have to click on "Search" on the project page, drop down the "Select a book" list. This shows the name of the file as the sole item in the list, i.e., "Tok Pisin fragment 1John.txt". I select that file, which then presents a "Select a chapter:" list that contains the following two items (presumably for chapter 1, which doesn't exist and chapter 2):

Tok Pisin fragment 1John.txt 1 Fully translated
Tok Pisin fragment 1John.txt 2 No translations (3 total verses)

The first document when opened only contains the following \id line:
1JN John Tok Pisin, fragment chapter 2:12 - 2:14
which is only the \id line from the file. Note that this \id line has no target adaptations, even though the description says, "Fully translated".
The second file is the actual file that I want to adapt. When opened, it has the entire document presented for adaptation and an accurate description "No translations (3 total verses)". I would have expected that only the second item should be shown on the project page, since it has the actual content of the document that was imported.
1. Start a Tok Pisin to English project.
2. Import the Tok Pisin fragment (a selection from chapter 2 of 1 John)
   [Tok Pisin fragment 1John.txt](https://github.com/adapt-it/adapt-it-mobile/files/63311/Tok.Pisin.fragment.1John.txt)
3. Select the "Tok Pisin fragment 1John.txt 1"  item on the project page. The document opens, but only contains the \id line.
4. In order to get the actual text that is contained in the file, one has to press the "Search" button which apparently causes the program to parse the actual chapter content, and then the user can see the actual document listed as "Tok Pisin fragment 1John.txt 2 No translations (3 total verses)"

Since many users will be adapting individual chapter files, the file listed on the initial project page should go directly to the actual document as the first option, rather than opening a truncated document that only contains an \id line.

**Comment by eb1** [comment] 2015-12-17 16:13
Hmm... this is an interesting one.

Our use case -- that of dealing with collaboration documents and documents split into chapters -- is already being dealt with. We disallow users from importing a random chapter file without first importing the first chapter of that same file. These split and collaboration files are in AI desktop (XML) format.

The file described in this issue is one of the sample USFM text fragments that are shipped with AI desktop. On their own, these sample files don't constitute a real use case -- I'd imagine users would either work with a whole source file (usfm or otherwise), or collaboration chapters in XML format. But since these are sample files distributed with AI desktop, people might be tempted to throw them at AIM to see what comes out. 

I'll put this in the needs prioritization pile for now; we'll need to discuss how likely it is that someone would be playing around with these files.

**Comment by pngbill** [comment] 2015-12-17 20:15
One reason I tried to import the Tok Pisin fragment file is that I am getting an error when I try to import a chapter collaboration XML document. The collaboration document is a single chapter (chapter 2 of Acts) that was produced by AID in collaboration with Paratext. The error on Import says, "Import failed for _Collab_45_ACT_CH02.xml Reason: undefined [OK["
Here is the collaboration file that I tried to import: 
[_Collab_45_ACT_CH02.xml.txt](https://github.com/adapt-it/adapt-it-mobile/files/65877/_Collab_45_ACT_CH02.xml.txt)
Note: Github won't let me attach an xml file, so I had to add an acceptable extension (.txt) to the file, which you'll need to remove before testing with it.

**Comment by eb1** [comment] 2015-12-17 20:40
@pngbill - aside from the unhelpful / bad error message, the behavior by design. The first chapter contains some necessary info that isn't included in subsequent chapters (name, etc.) - AIM prevents you from importing subsequent chapters before importing chapter 1 first.

The error message should say: "this is a collaboration document; please import the first chapter before importing this chapter." I'll investigate why it's not displaying that text.

**Comment by eb1** [comment] 2015-12-17 23:22
@pngbill - unhelpful error message found and fixed. One of the calls to importFail() wasn't sending the correct object (an Error object). :-)

**Comment by eb1** [comment] 2018-06-19 21:10
This is addressed by the fix for #246

**Closed by eb1** 2018-06-19 21:10 UTC
